name: Randome Awesome
favicon: null
layout_spectrum: 0.12529
typography_spectrum: 0.3527
title: Randome Awesome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0.23843391751870513
  saturation: 0.10008645965717733
  rhythmicContrast: 0.8721449822187424
purpose: []
